version: "2"
services:
  master:
    image: jenkinsci/blueocean:latest
    container_name: jenkins
    ports:
    - "8080:8080"
    - "50000:50000"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./war:/usr/share/jenkins
    - ./jenkins-data:/var/jenkins_home
    restart: always